[package]
org = "ballerina_exercism"
name = "database_large_expenses"
version = "0.1.0"
distribution = "2201.5.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "h2"
version = "2.0.206"
groupId = "com.h2database"
